const cards = [
    {
        title: "My First Portfolio",
        description: "This was my first attempt at creating a portfolio after learning about HTML and CSS.  See how far I have grown in my work!",
        photo: "./images/Portfolio1.png",
        repo: "https://github.com/agrastp/My-Portfolio",
        deploy: "https://agrastp.github.io/My-Portfolio/"
    },
    {
        title: "ShowTime",
        description: "This application provides users a website to search information on TV Shows. APIs used include TVMaze and WatchMode. The website contains a data base of TV shows and their information, as well as streaming mediums for each show. Links of well-known external websites such as Netflix, Disney etc... that provide a wider variety of TV shows and movie content are also provided at the bottom.",
        photo: "./images/Showtime.png",
        repo: "https://github.com/agrastp/SHOWtime_Website",
        deploy: "https://agrastp.github.io/SHOWtime_Website/"
    },
    {
        title: "Book Buzz",
        description: "Book Buzz is an application for readers to give review for well known books. Readers will create a protected login account with username and password to get full access to the application. Then a list of books will be provided for users to leave a review. Readers are also able to browse the application to see all reviews of the books provided on the site. When finished, users are able to log out.",
        photo: "./images/Bookbuzz.png",
        repo: "https://github.com/agrastp/book-review-application",
        deploy: "https://aqueous-plateau-25751-d19cd5ff4a3b.herokuapp.com/"
    },
    {
        title: "Work Scheduler",
        description: "In this application, you will find a work planner to type out your daily schedule. With a few changes, it could be altered as a schedule for any purpose. The schedule is for the typical work day from 9am-5pm. Enter in your todos for each hour, save, and it will be there when you open it later in the day. It is color coded to indicate whether todos/events are in the past (gray), present (red), or future (green). Refer to the date and time at the top of the page for quick reference.",
        photo: "./images/Work.png",
        repo: "https://github.com/agrastp/Work_Schedule",
        deploy: "https://agrastp.github.io/Work_Schedule/"
    },
    {
        title: "Weather Dashboard",
        description: "This is a five-day weather website that will generate the weather for any city you input. Once the city is entered, the API will retrieve the latitude and longitude data, then input it into the API to retrieve the 5-day weather data. Once a city has been searched, a button will be created for ease in future searches. Click any city button and current weather data about the city will be retrieved.",
        photo: "./images/Weather.png",
        repo: "https://github.com/agrastp/Weather_App",
        deploy: "https://agrastp.github.io/Weather_App/"
    },
    {
        title: "ReadMe Generator",
        description: "Using node.js and inquirer, a preformatted README is generated by answering a few questions in the terminal. Once all questions are answered, a new README file will be made, where edits to the text can be made as needed.",
        photo: "./images/Readme.png",
        repo: "https://github.com/agrastp/README_Generator",
    },
];

export default function PortfolioPage() {
    return (
      <div className="container">
        <h1 id="portfolio" className="m-5 p-20">Welcome to my Portfolio</h1>
        <div className="row">
          {cards.map((card) => (
            <div className="col-md-4 mb-4 d-flex flex-column" key={card.title}>
              <div className="card h-100 card border-info">
                <img className="card-img-top" src={`${card.photo}`} alt="Card image cap" />
                <div className="card-body d-flex flex-column">
                  <h5 className="card-title">{`${card.title}`}</h5>
                  <p className="card-text">{`${card.description}`}</p>
                  <div className="mt-auto">
                    <a href={`${card.repo}`} className="btn btn-dark">
                      Go to Repo
                    </a>
                  </div>
                  {card.deploy && (
                    <div className="mt-2">
                      <a href={`${card.deploy}`} className="btn btn-secondary">
                        Deploy
                      </a>
                    </div>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }